name: FlyPlugin
version: ${project.version}
main: me.coarr.flyplugin.FlyPlugin
api-version: 1.13
authors: [Coarr]
description: A Fly Plugin
commands:
  fly:
    description: Fly command gives access to fly to the player.
    usage: /<command>